name: baseline-eval
description: Evaluate baseline model with stratified K-fold CV

steps:
  - name: check-dependencies
    run: |
      if [ ! -f data/artifacts/model.bin ]; then
        echo "Error: model.bin not found. Run 'moola train' first."
        exit 1
      fi
      if [ ! -f data/processed/train.parquet ]; then
        echo "Error: train.parquet not found. Run 'moola ingest' first."
        exit 1
      fi
    description: Verify model and data exist

  - name: evaluate
    run: moola evaluate
    description: Run stratified 5-fold cross-validation
    depends_on: [check-dependencies]

  - name: verify-outputs
    run: |
      if [ ! -f data/artifacts/metrics.json ]; then
        echo "Error: metrics.json not created"
        exit 1
      fi
      if [ ! -f data/artifacts/confusion_matrix.csv ]; then
        echo "Error: confusion_matrix.csv not created"
        exit 1
      fi
      if [ ! -f data/artifacts/runs.csv ]; then
        echo "Error: runs.csv not created"
        exit 1
      fi
      echo "All evaluation artifacts created successfully"
      cat data/artifacts/metrics.json
    description: Verify evaluation outputs
    depends_on: [evaluate]

outputs:
  - data/artifacts/metrics.json
  - data/artifacts/confusion_matrix.csv
  - data/artifacts/runs.csv
  - data/logs/moola.log

notes: |
  Runs stratified K-fold cross-validation (k=5) on the full dataset.
  Outputs accuracy, precision, recall, F1 per fold and averaged.
  Appends tracking line to runs.csv with git SHA and metrics.
