# Jade_Compact Model Configuration
# moola-lstm-m-v1.0 // codename: Jade
# Production BiLSTM with uncertainty-weighted multi-task learning

model:
  name: jade
  input_size: 11         # keep actual value you use
  hidden_size: 64
  num_layers: 1
  bidirectional: true
  proj_head: true
  head_width: 64
  pointer_head:
    encoding: center_length

train:
  batch_size: 29
  dropout_input: 0.25
  dropout_recurrent: 0.65
  dropout_dense: 0.5
  mc_dropout_passes: 50

loss:
  kendall_uncertainty: true
  init_log_sigma_ptr: -0.30
  init_log_sigma_cls: 0.00

early_stop:
  metric: hit_at_pm3
  patience: 20

plateau:
  metric: hit_at_pm3
  factor: 0.5
  patience: 10
  min_lr: 1e-6

# Early stopping
early_stopping:
  patience: 20
  monitor: val_loss
  mode: min

# Augmentation (Stones doctrine)
augmentation:
  jitter:
    enabled: true
    sigma: 0.03
    prob: 0.8
  magnitude_warp:
    enabled: true
    sigma: 0.2
    knots: 4
    prob: 0.5
  multiplier: 3  # On-the-fly ×3

# Uncertainty quantification
uncertainty:
  mc_dropout:
    enabled: true
    n_passes: 50  # Stones: 50-100
    dropout_rate: 0.15
  temperature_scaling:
    enabled: true

# Evaluation gates (Stones thresholds)
gates:
  hit_at_3: 0.60  # ≥60%
  f1_macro: 0.50  # ≥0.50
  ece: 0.10  # <0.10
  joint_success: 0.40  # ≥40%

