# Jade Model Configuration
# moola-lstm-m-v1.0 // codename: Jade
# Production BiLSTM with uncertainty-weighted multi-task learning

# AGENTS.md Section 9: Config composition from base defaults
defaults:
  - _base: model
  - _base: augmentation
  - _base: uncertainty
  - _base: gates

# Model-specific overrides
model:
   name: jade
   hidden_size: 96
   num_layers: 1

# Training-specific overrides
train:
    batch_size: 32
    dropout_input: 0.3
    dropout_recurrent: 0.7
    dropout_dense: 0.6
    mc_dropout_passes: 50

# Loss-specific overrides
loss:
  kendall_uncertainty: true
  init_log_sigma_ptr: -0.30
  init_log_sigma_cls: 0.00

# Early stopping specific overrides
early_stop:
  metric: hit_at_pm3
  patience: 20

plateau:
  metric: hit_at_pm3
  factor: 0.5
  patience: 10
  min_lr: 1e-6

early_stopping:
  patience: 20
  monitor: val_loss
  mode: min

