# Multi-task Training Configuration
# For Enhanced SimpleLSTM with pointer prediction

# Data settings
data:
  input_features: 11  # RelativeTransform features
  sequence_length: 105
  batch_size: 29
  val_split: 0.15
  num_workers: 2

# Training loop
training:
  epochs: 60
  learning_rate: 3e-4
  weight_decay: 1e-5
  max_grad_norm: 1.5
  
  # Early stopping
  early_stopping:
    patience: 20
    monitor: val_loss
    mode: min
  
  # Learning rate scheduling
  scheduler:
    type: ReduceLROnPlateau
    mode: min
    factor: 0.5
    patience: 10
    threshold: 0.001
    cooldown: 0
    min_lr: 1e-6

# Multi-task loss settings
loss:
  type: uncertainty_weighted  # Options: uncertainty_weighted, manual
  manual_weights:
    type_alpha: 1.0
    pointer_beta: 0.7
  
  # Pointer loss settings
  pointer_loss: huber
  huber_delta: 0.08  # 8 timesteps transition
  
  # Classification loss settings
  classification_loss: cross_entropy
  class_weights: null  # Auto-balance or set manually
  pos_weight: 2.0  # For retracement class

# Augmentation pipeline
augmentation:
  enabled: true
  
  # Temporal augmentation
  jitter:
    enabled: true
    prob: 0.8
    sigma: 0.03
  
  magnitude_warp:
    enabled: true
    prob: 0.5
    sigma: 0.2
    knots: 4
  
  # Mixup/CutMix
  mixup:
    enabled: true
    alpha: 0.4
    cutmix_prob: 0.5
  
  # Latent mixup (after encoder)
  latent_mixup:
    enabled: true
    alpha: 0.4
    prob: 0.5

# Hardware and optimization
hardware:
  device: cuda
  use_amp: true  # Automatic mixed precision
  pin_memory: true

# Evaluation and monitoring
evaluation:
  eval_frequency: 1  # Evaluate every epoch
  compute_calibration: true
  calibration_bins: 10
  
  # Metrics to track
  metrics:
    - accuracy
    - joint_success_rate
    - hit@±3
    - center_mae
    - length_mae
    - ece
    - type_sigma
    - pointer_sigma

# Checkpointing
checkpointing:
  save_best: true
  save_last: true
  monitor: val_joint_success_rate
  mode: max
  save_dir: artifacts/checkpoints/

# Logging
logging:
  log_frequency: 50  # Log every 50 batches
  tensorboard: false
  wandb: false
  
# Reproducibility
seed: 42
deterministic: true