# Default configuration for MOOLA
# Stones 80/20 guide - essential defaults only

# Model defaults
model:
  hidden_size: 128
  num_layers: 1
  dropout: 0.5
  recurrent_dropout: 0.6
  
  # Multi-task defaults
  predict_pointers: false
  use_uncertainty_weighting: true  # CRITICAL: Always enable for production
  
  # Feature defaults
  input_features: 11  # RelativeTransform
  sequence_length: 105

# Training defaults
training:
  epochs: 60
  batch_size: 29
  learning_rate: 3e-4
  max_grad_norm: 1.5
  early_stopping_patience: 20
  val_split: 0.15

# Hardware defaults
hardware:
  device: cuda
  use_amp: true
  num_workers: 2

# Augmentation defaults
augmentation:
  jitter_prob: 0.8
  jitter_sigma: 0.03
  magnitude_warp_prob: 0.5
  magnitude_warp_sigma: 0.2

# Loss defaults
loss:
  huber_delta: 0.08
  pos_weight: 2.0

# Evaluation defaults
evaluation:
  calibration_bins: 10
  hit_tolerance: 3  # ±3 timesteps

# Paths
paths:
  data_dir: data/
  artifacts_dir: artifacts/
  checkpoints_dir: artifacts/checkpoints/
  results_file: experiment_results.jsonl

# Reproducibility
seed: 42