# Minimal Hydra config for moola CLI
# Most settings are overridden via command-line arguments

# Default settings (all can be overridden)
device: cuda
epochs: 50
batch_size: 256
seed: 42
hidden_dim: 128
mask_ratio: 0.15
mask_strategy: patch
input_dim: 4
