# Base Augmentation Configuration
# AGENTS.md: Stones doctrine for robust training

augmentation:
  jitter:
    enabled: true
    sigma: 0.03
    prob: 0.8
  magnitude_warp:
    enabled: true
    sigma: 0.2
    knots: 4
    prob: 0.5
  multiplier: 3  # On-the-fly ×3
  
# Validation: ensure augmentation doesn't introduce leakage
validation:
  causality_check: true
  max_jitter_sigma: 0.1  # Prevent excessive distortion
  max_warp_sigma: 0.5
